
{{- if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secretName }}
type: Opaque # This is the default type for secrets, it means that the data is stored as key-value pairs and the values are encoded in base64.
stringData: # This will automatically encode the values to base64, base64 is not encription, just a way to encode the data for kubernetes because kubernetes must store the data in base64 format.
  # Those lines are the secret date saved in key-value pairs. The key we get from the values.yaml file, and the block of the "Curly brackets" contains the key, and what came after the ":" is the value of the secret.
  {{ .Values.mysql.userKey }}: "calculator" 
  {{ .Values.mysql.passwordKey }}: "calculator123"
  {{ .Values.mysql.rootPasswordKey }}: "root123"
{{- end }}
